site_name: PatronusAI Python SDK
site_url: https://docs.patronus.ai/patronus-py
repo_name: patronus-ai/patronus-py
repo_url: https://github.com/patronus-ai/patronus-py
theme:
  logo: assets/boxwhite.svg
  favicon: assets/favicon-32x32.png
  name: material
  features:
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Initialization: getting-started/initialization.md
      - Quickstart: getting-started/quickstart.md
  - Observability:
      - Tracing: observability/tracing.md
      - Logging: observability/logging.md
  - Evaluations:
      - Evaluators: evaluations/evaluators.md
      - Patronus Evaluators: evaluations/patronus-evaluators.md
      - Batching Evaluations: evaluations/batching.md
#  - Experiments:
#      - Running: ...
#      - Datasets: experiments/datasets.md
  - Configuration: configuration.md
  - API Reference:
      - tracing: api_ref/tracing.md
      - evals: api_ref/evals.md
      - experiments: api_ref/experiments.md
      - api_client: api_ref/api_client.md
      - pat_client: api_ref/pat_client.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            allow_inspection: true
            members_order: source
            separate_signature: true
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            show_signature_annotations: true
            signature_crossrefs: true
